name: Workflow Filters and Activities

on:
    workflow_dispatch: 
    
    push:
        branches:
            - main
            - '!feature/*' #ignoring(!) push to this branch, can also use the "branches-ignore"
    
    
    pull_request: 
        types:
        - opened
        - closed
        paths-ignore: 
        - README.md
        branches:
            - main
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - run: echo this workflow/job/setup is executed for event type - ${{ github.event_name }}